#!/bin/sh
# Queenix Gym — one-command local run.
#
#   ./scripts/dev-up.sh
#
# Starts Convex backend + function sync + web admin + Expo (Metro) + demo
# seed, then prints the web address and where to find the Expo QR code.
# Everything is local; Stripe/Tap stay in mock mode.
#
# Hot paths:
#   Web admin   http://<LAN-IP>:3000/login   (demo password QueenixDemo123!)
#   Convex dash http://<LAN-IP>:6791
#   Mobile      scan the QR in `docker logs -f queenix-expo` with Expo Go
set -eu

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

if ! docker info >/dev/null 2>&1; then
  echo "✗ Docker daemon is not running."
  echo "  Open Docker Desktop and wait until it says running, then re-run:"
  echo "    ./scripts/dev-up.sh"
  exit 1
fi

# --- host LAN IP (phones + containers reach this; container-localhost does not)
LAN_IP=""
if command -v ipconfig >/dev/null 2>&1; then
  LAN_IP="$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || true)"
fi
if [ -z "$LAN_IP" ] && command -v hostname >/dev/null 2>&1; then
  LAN_IP="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"
fi
if [ -z "$LAN_IP" ]; then
  echo "Could not detect LAN IP; falling back to localhost."
  echo "(Phone testing needs the real LAN IP — set EXPO_HOST_IP manually.)"
  LAN_IP="localhost"
fi

# --- free host ports held by stale local servers (compose is untouched)
for p in 3000 8081 19002; do
  pids="$(lsof -ti:$p 2>/dev/null || true)"
  if [ -n "$pids" ]; then
    # shellcheck disable=SC2086
    kill -9 $pids 2>/dev/null || true
    echo "freed host port $p"
  fi
done

# --- clear stale Next build cache (fixes vendor-chunks ENOENT 500s)
rm -rf apps/web/.next

# --- env for compose (AUTH_BASE_URL must be LAN-reachable: the Convex
# --- container fetches OIDC discovery from it to verify login tokens)
cat > .env.docker <<EOF
# Generated by scripts/dev-up.sh — do not edit by hand (re-run the script).
AUTH_BASE_URL=http://$LAN_IP:3000
NEXT_PUBLIC_CONVEX_URL=http://$LAN_IP:3210
EXPO_PUBLIC_CONVEX_URL=http://$LAN_IP:3210
EXPO_PUBLIC_AUTH_BASE_URL=http://$LAN_IP:3000
EXPO_HOST_IP=$LAN_IP
EOF

echo "LAN IP: $LAN_IP"
docker compose --env-file .env.docker up -d --build

# --- point the Convex deployment at this host.
# Convex bakes the accepted JWT issuer (auth.config) from DEPLOYMENT env
# (`npx convex env`), not from container env — so after (re)starting the
# stack we must sync it, or every query fails with UNAUTHORIZED.
# convex-sync re-pushes the bundle on restart.
if [ -f packages/convex/.env.local ]; then
  CURRENT_ISSUER="$(cd packages/convex && npx convex env list 2>/dev/null | grep '^AUTH_BASE_URL=' | cut -d= -f2- || true)"
  if [ "$CURRENT_ISSUER" != "http://$LAN_IP:3000" ]; then
    echo "Syncing Convex issuer to http://$LAN_IP:3000 ..."
    (cd packages/convex && npx convex env set AUTH_BASE_URL "http://$LAN_IP:3000" >/dev/null 2>&1 || true)
    docker compose --env-file .env.docker restart convex-sync >/dev/null 2>&1 || true
  fi
fi

echo ""
echo "Waiting for web + expo to come up (first build takes a few minutes)..."
sleep 5

echo ""
echo "================ QUEENIX GYM IS UP ================"
echo "Web admin : http://$LAN_IP:3000/login"
echo "  owner@queenix.test / ops@queenix.test /"
echo "  trainer@queenix.test / member@queenix.test"
echo "  password for all: QueenixDemo123!"
echo "Convex dash: http://$LAN_IP:6791"
echo "Mobile    : scan the QR below with Expo Go (same Wi-Fi)"
echo "==================================================="
echo ""
docker logs --tail 5 queenix-expo 2>/dev/null || true
echo ""
echo "Live QR + Metro logs:  docker logs -f queenix-expo"
echo "Seed status:           docker logs queenix-seed"
echo "Stop everything:       docker compose down"
